In [2]:
import pandas as pd

In [6]:
df = pd.read_csv(r'C:\Users\patel\Downloads\Desktop\New folder\customer-trends-data-analysis-SQL-Python-PowerBI-main\customer-trends-data-analysis-SQL-Python-PowerBI-main\customer_shopping_behavior.csv')
df.head(2)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [13]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [14]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [20]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group'],
      dtype='str')

In [77]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [78]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [24]:
#create a column age_group
labels = ['young adult','adult','middle-aged','senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [25]:
df[['age','age_group']].head(10)

   age    age_group
0   55  middle-aged
1   19  young adult
2   50  middle-aged
3   21  young adult
4   45  middle-aged
5   46  middle-aged
6   63       senior
7   27  young adult
8   26  young adult
9   57  middle-aged

In [27]:
df['frequency_of_purchases'].unique().tolist()

['Fortnightly',
 'Weekly',
 'Annually',
 'Quarterly',
 'Bi-Weekly',
 'Monthly',
 'Every 3 Months']

In [50]:

frequency_mappinng = {
    'fortnigtly' : 14,
    'weekly' : 7,
    'monthly' : 30,
    'quartly' : 90,
    'bi-Weekly' : 365,
    'every 3 Months' : 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            fortnightly
1                     14.0            fortnightly
2                      7.0                 weekly
3                      7.0                 weekly
4                    365.0               annually
5                      7.0                 weekly
6                     90.0              quarterly
7                      7.0                 weekly
8                    365.0               annually
9                     90.0              quarterly

In [51]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [54]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [58]:
(df['discount_applied']==df['promo_code_used']).all

<bound method Series.all of 0       True
1       True
2       True
3       True
4       True
        ...
3895    True
3896    True
3897    True
3898    True
3899    True
Length: 3900, dtype: bool>

In [59]:
df = df.drop('promo_code_used',axis = 1)

In [60]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [65]:
#To Connect Jupyter to PostGre SQL
#1. Install the SQLAlchemy and PyschoPG2-binary

pip install sqlalchemy psycopg2-binary

Collecting sqlalchemy
  Downloading sqlalchemy-2.1.5-cp315-cp315-win_amd64.whl.metadata (9.9 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp315-cp315-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\patel\AppData\Local\Python\pythoncore-3.15-64\Lib\site-packages (from sqlalchemy) (4.16.0)
Downloading sqlalchemy-2.1.5-cp315-cp315-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   -------- ------------------------------- 0.5/2.4 MB 44.4 kB/s eta 0:00:44
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ------------ --------------------------- 0.8/2.4 MB 42.5 kB/s eta 0:00:39
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   ----------------- ---------------------- 1.0/2.4 MB 41.9 kB/s eta 0:00:34
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   --------------------- ------------------ 1.3/2.4 MB 42.3 kB/s eta 0:00:27
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------- -------------- 1.6/2.4 MB 39.7 kB/s eta 0:00:22
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ------------------------------ --------- 1.8/2.4 MB 40.0 kB/s eta 0:00:16
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   ---------------------------------- ----- 2.1/2.4 MB 42.3 kB/s eta 0:00:09
   -------------------------------------- - 2.4/2.4 MB 44.9 kB/s eta 0:00:02
   -------------------------------------- - 2.4/2.4 MB 44.9 kB/s eta 0:00:02
   -------------------------------------- - 2.4/2.4 MB 44.9 kB/s eta 0:00:02
   -------------------------------------- - 2.4/2.4 MB 44.9 kB/s eta 0:00:02
   -------------------------------------- - 2.4/2.4 MB 44.9 kB/s eta 0:00:02
   -------------------------------------- - 2.4/2.4 MB 44.9 kB/s eta 0:00:02

In [79]:
from sqlalchemy import create_engine

#Step 1 : Connect to PostGreSql
username = "postgres"
password = "1101"
host = "localhost"
port = "5433"
database = "customer_behaviour"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name,engine,if_exists = "replace",index = False)
print(f"Data Successfully loaded into table '{table_name}' in database'{database}' ")

Data Successfully loaded into table 'customer' in database'customer_behaviour'